**Q1.** Sales & Commission Analysis
 You are given the revenue (in 
Laptops, Mobiles, and Tablets.
 Use NumPy arrays to:
 lakhs) and expenses (in 
1. Calculate the profit for each item.
 2. Find the average profit.
 lakhs) for three electronic items:
 3. Given a commission percentage array [5, 7, 10], calculate the total commission amount for each
 item.
 4. Display all results in a formatted output using OOP (create a Product class)

In [4]:
import numpy as np

# Step 1: Define the Product class
class Product:
    def __init__(self, names, revenue, expenses, commission_rates):
        self.names = np.array(names)
        self.revenue = np.array(revenue)
        self.expenses = np.array(expenses)
        self.commission_rates = np.array(commission_rates)
        
    def calculate_profit(self):
        self.profit = self.revenue - self.expenses
        return self.profit
    
    def average_profit(self):
        return np.mean(self.profit)
    
    def calculate_commission(self):
        # Commission = (profit × rate%) / 100
        self.commission = (self.profit * self.commission_rates) / 100
        return self.commission
    
    def display_results(self):
        print("Product Performance Report")
        print("--------------------------")
        for i in range(len(self.names)):
            print(f"Product: {self.names[i]}")
            print(f"Revenue: ₹{self.revenue[i]} Lakhs")
            print(f"Expense: ₹{self.expenses[i]} Lakhs")
            print(f"Profit: ₹{self.profit[i]:.2f} Lakhs")
            print(f"Commission: ₹{self.commission[i]:.2f} Lakhs")
            print("--------------------------")
        print(f"Average Profit: ₹{self.average_profit():.2f} Lakhs")

# Step 2: Input data
product_names = ['Laptops', 'Mobiles', 'Tablets']
revenue = [120, 100, 80]       # in lakhs
expenses = [70, 60, 50]        # in lakhs
commission_rates = [5, 7, 10]  # in %

# Step 3: Create object
products = Product(product_names, revenue, expenses, commission_rates)

# Step 4: Perform calculations
products.calculate_profit()
products.calculate_commission()

# Step 5: Display results
products.display_results()


Product Performance Report
--------------------------
Product: Laptops
Revenue: ₹120 Lakhs
Expense: ₹70 Lakhs
Profit: ₹50.00 Lakhs
Commission: ₹2.50 Lakhs
--------------------------
Product: Mobiles
Revenue: ₹100 Lakhs
Expense: ₹60 Lakhs
Profit: ₹40.00 Lakhs
Commission: ₹2.80 Lakhs
--------------------------
Product: Tablets
Revenue: ₹80 Lakhs
Expense: ₹50 Lakhs
Profit: ₹30.00 Lakhs
Commission: ₹3.00 Lakhs
--------------------------
Average Profit: ₹40.00 Lakhs


------------------------------------------------------------------------------------------------------
 
 **Q2.** Manufacturing Cost Optimization
 A factory produces 4 types of sensors. The cost of materials and labor are stored in NumPy arrays:
 materials = np.array([120, 150, 180, 200])
 labor = np.array([80, 70, 90, 100])
 1. Calculate total production cost per sensor.
 2. If the selling price per sensor is [250, 260, 290, 320], find profit per sensor.
 3. Compute the maximum and minimum profit using NumPy functions

In [11]:
materials = np.array([120, 150, 180, 200]) 
labor = np.array([80, 70, 90, 100])
production_cost = materials + labor
print(production_cost)
print(type(production_cost))
sp = np.array([250, 260, 290, 320])
profit = sp - production_cost
print(profit)

print(np.max(profit))
print(np.min(profit))

[200 220 270 300]
<class 'numpy.ndarray'>
[50 40 20 20]
50
20


 **Q3.** Student Score Evaluation
 Create NumPy arrays to store marks of 5 students in three subjects:
 maths = np.array([78, 85, 92, 68, 90])
 science = np.array([80, 83, 88, 70, 85])
 english = np.array([75, 89, 90, 72, 88])
 1. Calculate the total and average marks for each student.
 2. Find which student scored the highest average.
 3. Use OOP to create a class Student that prints the result of a student when roll number is given.

In [13]:
import numpy as np

class Student:
    def __init__(self, roll_numbers, maths, science, english):
        self.roll_numbers = np.array(roll_numbers)
        self.maths = np.array(maths)
        self.science = np.array(science)
        self.english = np.array(english)
        
        # Calculate total and average marks
        self.total_marks = self.maths + self.science + self.english
        self.average_marks = self.total_marks / 3
        
    def show_all_results(self):
        print("Student Results Summary")
        print("-----------------------")
        for i in range(len(self.roll_numbers)):
            print(f"Roll No: {self.roll_numbers[i]}")
            print(f"Maths: {self.maths[i]}, Science: {self.science[i]}, English: {self.english[i]}")
            print(f"Total: {self.total_marks[i]}, Average: {self.average_marks[i]:.2f}")
            print("-----------------------")
        
        # Highest average
        highest_index = np.argmax(self.average_marks)
        print(f"Highest Average Scorer: Roll No {self.roll_numbers[highest_index]} with Average {self.average_marks[highest_index]:.2f}\n")
    
    def show_student_result(self, roll_no):
        if roll_no in self.roll_numbers:
            i = np.where(self.roll_numbers == roll_no)[0][0]
            print(f"Result for Roll No {roll_no}")
            print("-----------------------")
            print(f"Maths: {self.maths[i]}")
            print(f"Science: {self.science[i]}")
            print(f"English: {self.english[i]}")
            print(f"Total Marks: {self.total_marks[i]}")
            print(f"Average Marks: {self.average_marks[i]:.2f}")
        else:
            print("Invalid Roll Number!")



roll_numbers = [1, 2, 3, 4, 5]
maths = np.array([78, 85, 92, 68, 90])
science = np.array([80, 83, 88, 70, 85])
english = np.array([75, 89, 90, 72, 88])

students = Student(roll_numbers, maths, science, english)

# Display all results
students.show_all_results()

# Show result for a specific student (for example Roll No 3)
students.show_student_result(3)

        

Student Results Summary
-----------------------
Roll No: 1
Maths: 78, Science: 80, English: 75
Total: 233, Average: 77.67
-----------------------
Roll No: 2
Maths: 85, Science: 83, English: 89
Total: 257, Average: 85.67
-----------------------
Roll No: 3
Maths: 92, Science: 88, English: 90
Total: 270, Average: 90.00
-----------------------
Roll No: 4
Maths: 68, Science: 70, English: 72
Total: 210, Average: 70.00
-----------------------
Roll No: 5
Maths: 90, Science: 85, English: 88
Total: 263, Average: 87.67
-----------------------
Highest Average Scorer: Roll No 3 with Average 90.00

Result for Roll No 3
-----------------------
Maths: 92
Science: 88
English: 90
Total Marks: 270
Average Marks: 90.00


------------------------------------------------------------------------------------------------------

**Q4**  Medicine Production Analysis
 A pharmaceutical company produces 3 types of medicines.
 The data for production cost, selling price, and units sold are:
 cost = np.array([12, 8, 10])
 price = np.array([20, 15, 18])
 sold = np.array([5000, 8000, 6000])
 1. Calculate profit per medicine.
 2. Calculate total profit for all medicines.
 3. Compute the mean, median, and standard deviation of profits.

In [15]:
cost = np.array([12, 8, 10])
price = np.array([20, 15, 18])
sold = np.array([5000, 8000, 6000])

profit = (price - cost)*sold
print(f" profit per medicine : {profit}")

total_profit = np.sum(profit)
print(f"total profit for all medicines : {total_profit}")

print(np.mean(profit))
print(np.median(profit))
print(np.std(profit))


 profit per medicine : [40000 56000 48000]
total profit for all medicines : 144000
48000.0
48000.0
6531.972647421808


------------------------------------------------------------------------------------------------------

**Q5.**  Monthly Temperature Analysis
 Given temperature readings (in °C) for 12 months of a city:
 temps = np.array([22, 24, 29, 33, 36, 38, 37, 35, 32, 28, 25, 23])
 1. Calculate the average temperature of the year.
 2. Find months where temperature was above average.
 3. Calculate the temperature difference between consecutive months

In [19]:
temps = np.array([22, 24, 29, 33, 36, 38, 37, 35, 32, 28, 25, 23])
avg_temp = np.mean(temps)
print(avg_temp)
print(temps[temps > avg_temp])
for i in range(0,len(temps)-1):
    print(temps[i+1] - temps[i])

30.166666666666668
[33 36 38 37 35 32]
2
5
4
3
2
-1
-2
-3
-4
-3
-2


------------------------------------------------------------------------------------------------------
 
 **Q6.** For 4 households, the units consumed are:
 units = np.array([350, 420, 180, 500])
 and the per-unit rate is 6.5.
 1. Calculate the total bill using NumPy operations.
 2. If the government gives a subsidy of 5% on bills above 2500, calculate the new bill amount for
 each house

In [21]:
units = np.array([350, 420, 180, 500])
per_unit_rate = 6.5

total_bill = units * per_unit_rate
print(total_bill)

total_bill[total_bill > 2500 ]  *= 0.95
print(total_bill)

[2275. 2730. 1170. 3250.]
[2275.  2593.5 1170.  3087.5]


------------------------------------------------------------------------------------------------------

**Q7** Fitness Tracker Data
 You have NumPy arrays storing the number of calories burnt per day for a week:
 user1 = np.array([320, 450, 400, 500, 600, 550, 480])
 user2 = np.array([300, 420, 380, 470, 580, 540, 460])
 1. Compute total calories burnt by each user.
 2. Calculate which user maintained a more consistent performance (less standard deviation)

In [23]:
user1 = np.array([320, 450, 400, 500, 600, 550, 480])
user2 = np.array([300, 420, 380, 470, 580, 540, 460])

print(f"total calories burnt by user 1 by {np.sum(user1)}")
print(f"total calories burnt by user 2 by {np.sum(user2)}")

if np.std(user1) < np.std(user2) :
    print("user 1 maintained a more consistent performance")
elif np.std(user2) < np.std(user1) :
    print("user 2 maintained a more consistent performance")
else:
    print("Both users maintained equally consistent performance")

total calories burnt by user 1 by 3300
total calories burnt by user 2 by 3150
user 1 maintained a more consistent performance


------------------------------------------------------------------------------------------------------

**Q8.** OOP + NumPy Integration
 Create a Product class with attributes name, cost, and price.
 Use NumPy arrays to store multiple products and:
 1. Compute profit percentage for each.
 2. Display product with maximum profit

In [25]:
class Product:
    def __init__(self , name , cost , price):
        self.name = np.array(name)
        self.cost = np.array(cost)
        self.price = np.array(price)

    def profit_percentage(self):
        self.profit = ((self.price - self.cost ) / self.cost) * 100
        return (f" profit percentage for each product is {self.profit}")

p1 = Product(['a','b','c'],[12,34,98],[34,57,120])
print(p1.profit_percentage())
max_p_index = np.argmax(p1.profit)
print(p1.name[max_p_index])

    

 profit percentage for each product is [183.33333333  67.64705882  22.44897959]
a


------------------------------------------------------------------------------------------------------

**Q9**. Employee Salary Adjustment
 An array stores base salaries of employees:
 salary = np.array([45000, 52000, 60000, 48000, 75000])
 1. Increase salary by 10% for those earning below 50,000.
 2. Calculate the new mean salary.
 3. Find the difference between highest and lowest salary after increment

In [29]:
salary = np.array([45000, 52000, 60000, 48000, 75000] , dtype = 'float64')

salary_filter = salary < 50_000
salary[salary_filter] *= 1.1
print(salary)
print(np.mean(salary))
print(np.max(salary) - np.min(salary))

[49500. 52000. 60000. 52800. 75000.]
57860.0
25499.999999999993


------------------------------------------------------------------------------------------------------

**Q 10**  An investor invests in 4 companies:
 investment = np.array([100000, 150000, 120000, 180000])
 returns = np.array([110000, 160000, 130000, 200000])
 1. Calculate the return percentage for each.
 2. Find the average return percentage.
 3. Use NumPy logical operations to identify which companies gave >10% return

In [40]:
companies = np.array(['a' , 'b', 'c', 'd'])
investment = np.array([100000, 150000, 120000, 180000]) 
returns = np.array([110000, 160000, 130000, 200000])

return_percentage =(( returns - investment) / investment) * 100
print(return_percentage)

avg_return_percentage =  np.mean(return_percentage)
high_return_mask = return_percentage > 10
print(companies[high_return_mask])

[10.          6.66666667  8.33333333 11.11111111]
['d']
